---
title: "Proteomics, transcriptomics and radiomics data integration"
author: "Mafe Senosain"
date: "9/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE)
```

```{r}
library(ComplexHeatmap)
library(circlize)
library(tidyverse)
library(dplyr)
library(RCy3)
library(igraph)
library(cluster)
library(factoextra)
source('src/cytof/20_ClustAnnot_functions.R')
```

```{r}
all_vars_scaled <- read.csv('data/TMA36_project/data_integration/cytof_rna_hm.csv', row.names = 1)
all_vars_raw <- read.csv('data/TMA36_project/data_integration/cytof_rna_hm_raw.csv', row.names = 1)
colnames(all_vars_scaled) = gsub('\\.', ' ', colnames(all_vars_scaled))
clusters_patients <- read.csv('data/TMA36_project/data_integration/clusters_patients.csv', row.names = 1)
clusters_features <- read.csv('data/TMA36_project/data_integration/clusters_features.csv', row.names = 1)
CDE = read.csv('data/TMA36_project/CDE/CDE_TMA36_2020FEB25_SA_MF.csv')
CDE = CDE[match(rownames(all_vars_scaled), CDE$pt_ID),]
```

```{r}
wes = read.csv("data/TMA36_project/WES/processed/wes_binary.csv")
colnames(wes)[1] = 'pt_ID'
CDE = left_join(CDE, wes, by = 'pt_ID')
```

```{r}
col_bh = c('ind' = '#3498DB', 'int' = 'grey72', 'agg'= '#EC7063')
col_sila = colorRamp2(c(0, 0.5, 1), c("white", "#653e87", "#0d0514"))
col_stage = c('Stage 0'='#42f5f2', 'Stage I'='#53d94c', 'Stage II' = '#e8a62c', 'Stage III' = '#e85e2c')

ha = HeatmapAnnotation(
  Behavior = as.factor(CDE$n_op2),
  SILA = CDE$SILA,
  Sex = CDE$Gender,
  Stage = CDE$Stages_simplified,
  Nodule_size = CDE$Path_Nodule_Size_cm,
  Histology = CDE$Hist_predominant,
  Smoking = CDE$Smoking_Status,
  Pack_Yrs = CDE$Pack_Years,
  Log_mut_load = log(CDE$mut_load),
  KRAS = as.factor(CDE$KRAS),
  EGFR = as.factor(CDE$EGFR),
  col = list(Behavior = col_bh, 
             SILA = col_sila,
             Stage = col_stage),
  simple_anno_size = unit(0.5, "cm")
)

```

## Zoom out
```{r, fig.width = 10, fig.height = 6}
set.seed(0)
Heatmap(t(all_vars_scaled), name = "z-score",
        heatmap_legend_param = list(color_bar = "continuous"), 
        row_names_gp = gpar(fontsize = 8),
        column_names_gp = gpar(fontsize = 8),
        row_split = clusters_features$cluster,
        show_row_dend = FALSE,
        column_split = clusters_patients$cluster,
        top_annotation = ha, show_row_names = F)

```

## Zoom in
```{r, fig.width = 10, fig.height = 40}
set.seed(0)
Heatmap(t(all_vars_scaled), name = "z-score",
        heatmap_legend_param = list(color_bar = "continuous"), 
        row_names_gp = gpar(fontsize = 8),
        column_names_gp = gpar(fontsize = 8),
        row_split = clusters_features$cluster,
        column_split = clusters_patients$cluster,
        top_annotation = ha, show_row_names = T)

```

