---
title: "Summary of TMA36 cohort: clinical characteristics"
author: "Mafe Senosain"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(reshape2)
library(jcolors)
library(ComplexHeatmap)
library(dplyr)
library(tidyr)
library(ggrepel)
library(forcats)
library(ggsignif)
library(ggpubr)
library(circlize)

source("src/cytof/20_ClustAnnot_functions.R")
# source("src/cytof/")
# source("/Users/senosam/Documents/Repositories/Research/data_analysis_cytof/R/20_ClustAnnot_functions.R")
# source("/Users/senosam/Documents/Repositories/Research/data_analysis_cytof/R/30_DA_functions.R")
# source("/Users/senosam/Documents/Repositories/Research/data_analysis_cytof/R/40_DE_functions.R")
```

```{r, echo=FALSE}
# read edited CSV file as CDE_TMA36
CDE <- read.csv(file = 'data/TMA36_project/CDE/CDE_TMA36_2021SEPT21_DR_MF.csv')
CDE$n_op2 <- factor(CDE$n_op2, levels = c('ind', 'int', 'agg'))
CDE = CDE[-which(CDE$pt_ID =='11840'),] # remove 11840, no radiomics data

```

```{r, echo=FALSE}
pie_chart <- function(dt, col_name, plot_title){
    x <- data.frame(table(dt[col_name]))
    colnames(x) <- c('Group', 'value')
    x <- x %>% 
        arrange(desc(value)) #%>%
        #mutate(prop = label_percent(value / sum(value)))

    print(ggplot(x, aes(x = "", y = value, fill = fct_inorder(Group))) +
        geom_bar(width = 1, stat = "identity") +
        coord_polar("y", start = 0) +
        geom_label_repel(aes(label = value), size=5, show.legend = F, nudge_x = 1) +
        #geom_label_repel(aes(label = prop), size=5, show.legend = F, nudge_x = 1) + #%
        guides(fill = guide_legend(title = "Group")) +
        labs(title=plot_title) +
        theme(plot.title = element_text(hjust = 0.5, size=22)))
}

```

# Clinical characteristics distributions on TMA36 cohort
```{r, echo=FALSE}
hist(CDE$SILA, xlab="SILA score", main = 'SILA Score', xlim=c(0,1), col="chocolate", border="brown", las=1, xaxt = "n")
axis(1, at = seq(0, 1, .1))
pie_chart(CDE, 'n_op2', 'Behavior (categorical)')
pie_chart(CDE, 'Stages_simplified', 'Stage')
pie_chart(CDE, 'Hist_predominant', 'Histology')
pie_chart(CDE, 'Death_st', 'Death Status')
pie_chart(CDE, 'Recurrence_st', 'Recurrence Status')
pie_chart(CDE, 'Progression_st', 'Progression Status')
pie_chart(CDE, 'Smoking_Status', 'Smoking Status')
```

# Clinical characteristics distributions by CANARY

## Good prognosis (Indolent)
```{r, echo=FALSE}
k <- which(CDE$n_op2 == 'ind')
hist(CDE$SILA[k], xlab="SILA score", main = 'SILA Score', xlim=c(0,1), col="chocolate", border="brown", las=1, xaxt = "n")
axis(1, at = seq(0, 1, .1))
pie_chart(CDE[k,], 'Stages_simplified', 'Stage')
pie_chart(CDE[k,], 'Hist_predominant', 'Histology')
pie_chart(CDE[k,], 'Death_st', 'Death Status')
pie_chart(CDE[k,], 'Recurrence_st', 'Recurrence Status')
pie_chart(CDE[k,], 'Progression_st', 'Progression Status')
pie_chart(CDE[k,], 'Smoking_Status', 'Smoking Status')

```

## Intermediate prognosis
```{r, echo=FALSE}
k <- which(CDE$n_op2 == 'int')
hist(CDE$SILA[k], xlab="SILA score", main = 'SILA Score', xlim=c(0,1), col="chocolate", border="brown", las=1, xaxt = "n")
axis(1, at = seq(0, 1, .1))
pie_chart(CDE[k,], 'Stages_simplified', 'Stage')
pie_chart(CDE[k,], 'Hist_predominant', 'Histology')
pie_chart(CDE[k,], 'Death_st', 'Death Status')
pie_chart(CDE[k,], 'Recurrence_st', 'Recurrence Status')
pie_chart(CDE[k,], 'Progression_st', 'Progression Status')
pie_chart(CDE[k,], 'Smoking_Status', 'Smoking Status')
```

## Poor prognosis (Aggressive)
```{r, echo=FALSE}
k <- which(CDE$n_op2 == 'agg')
hist(CDE$SILA[k], xlab="SILA score", main = 'SILA Score', xlim=c(0,1), col="chocolate", border="brown", las=1, xaxt = "n")
axis(1, at = seq(0, 1, .1))
pie_chart(CDE[k,], 'Stages_simplified', 'Stage')
pie_chart(CDE[k,], 'Hist_predominant', 'Histology')
pie_chart(CDE[k,], 'Death_st', 'Death Status')
pie_chart(CDE[k,], 'Recurrence_st', 'Recurrence Status')
pie_chart(CDE[k,], 'Progression_st', 'Progression Status')
pie_chart(CDE[k,], 'Smoking_Status', 'Smoking Status')
```

# Clinical characteristics distributions by SILA Score

```{r, echo=FALSE}
#http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/76-add-p-values-and-significance-levels-to-ggplots/
bp_f <- function(dt, chr_colnm, sila_colnm='SILA', main_title, x_title) {
  dt <- dt[,c(sila_colnm,chr_colnm)]
  dt <- melt(dt)
  colnames(dt)[1]<- 'condition'
  
  x <- compare_means(value ~ condition, dt, method = "wilcox.test", paired = FALSE,
                     group.by = NULL, ref.group = NULL)
  idx <- which(x$p.signif != 'ns')
  ls <- list()
  n=1
  for (i in idx) {
    ls[[n]] <- c(x$group1[idx[n]], x$group2[idx[n]])
    n=n+1
  }
  #print(data.frame(x))
  
  p <- ggplot(dt, aes(x=condition, y=value, fill=condition)) +
    geom_boxplot() +
    labs(title=main_title,x=x_title, y = "SILA score") +
    theme(plot.title = element_text(hjust = 0.5, size=20)) +
    ggsignif::geom_signif(comparisons = ls, 
       map_signif_level=TRUE)
    geom_signif(comparisons = ls, 
              map_signif_level=TRUE)
  return(p)
}

bp_f(CDE, chr_colnm='n_op2', sila_colnm='SILA', main_title='SILA score by Behavior (categorical)', x_title='SILA Group')
bp_f(CDE, chr_colnm='Stages_simplified', sila_colnm='SILA', main_title='SILA score by Stage', x_title='Tumor Stage')
bp_f(CDE, chr_colnm='Hist_predominant', sila_colnm='SILA', main_title='SILA score by Histology', x_title='Predominant Histology')
bp_f(CDE, chr_colnm='Death_st', sila_colnm='SILA', main_title='SILA score by Death Status', x_title='Death Status')
bp_f(CDE, chr_colnm='Recurrence_st', sila_colnm='SILA', main_title='SILA score by Recurrence Status', x_title='Recurrence Status')
bp_f(CDE, chr_colnm='Progression_st', sila_colnm='SILA', main_title='SILA score by Progression Status', x_title='Progression Status')
bp_f(CDE, chr_colnm='Smoking_Status', sila_colnm='SILA', main_title='SILA score by Smoking Status', x_title='Smoking Status')


```

```{r}
ggpubr::ggscatter(CDE, x = 'SILA', y = c("Age_at_collection"),
          add = "reg.line", conf.int = TRUE, combine = TRUE,
          cor.coef = TRUE, cor.method = "spearman", add.params = list(color = 'grey'),
          xlab = "SILA score", ylab = 'Age_at_collection')
```

# Plots for paper

## Summary Omics datasets heatmap

```{r}
# Load data
df_cytof <- read.csv(file = 'data/TMA36_project/CyTOF/processed/Data_paper2/both/cytof_medianprot.csv', row.names = 1)
df_rna <- read.csv(file = 'data/TMA36_project/RNA_Seq/processed/TF_VIPER_all.csv', row.names = 1)
df_wes <- read.csv(file = 'data/TMA36_project/WES/processed/wes_binary.csv', row.names = 1)
df_rad <- read.csv(file = 'data/TMA36_project/Radiomics/processed/rad_healthmyne.csv', row.names = 1)
```

```{r}
CDE_omics <- CDE
CDE_omics['cytof'] <- 0
CDE_omics[which(CDE$pt_ID %in% rownames(df_cytof)),'cytof'] <- 1
CDE_omics['rnaseq'] <- 0
CDE_omics[which(CDE$pt_ID %in% rownames(df_rna)),'rnaseq'] <- 1
CDE_omics['wes'] <- 0
CDE_omics[which(CDE$pt_ID %in% rownames(df_wes)),'wes'] <- 1
CDE_omics['mxif'] <- 1
sc_rna <- c('12929', '13774', '14965', '12889', '8356', 
            '11918', '11522', '15002', '15467', '13634', '14428',
            '11817', '14958', '12935', '13636') #'7984' not included, low quality
CDE_omics['scrnaseq'] <- 0
CDE_omics[which(CDE$pt_ID %in% sc_rna),'scrnaseq'] <- 1
rownames(CDE_omics) <- CDE_omics$pt_ID
CDE_omics <- CDE_omics[,which(colnames(CDE_omics)=='cytof'):ncol(CDE_omics)]
```


```{r, fig.width = 12, fig.height = 5}
mat = t(as.matrix(CDE_omics))

# colors
col_prog = c('ind' = '#3498DB', 'int' = 'grey72', 'agg'= '#c75264')
col_sila = colorRamp2(c(0, 0.5, 1), c("white", "#6772c7", "#0f1547"))
col_stage = c('Stage 0'='#465362', 'Stage I'='#011936', 'Stage II' = '#c2eabd', 'Stage III' = '#f9dc5c', 'Stage IV' = '#ED254E')
col_hist = c('acinar'='#FFBF00', 'lepidic'='#f5ecda', 'micropapillary'='#2274A5', 'mucinous acinar'='#32936F', 'papillary'='#5C5C5C', 'solid'='#E83F6F')
col_smok = c('Current smoker'='#0FA3B1','Ex-smoker'='#B5E2FA','Never smoked'='#EDDEA4')
col_nodsiz = colorRamp2(c(0.5, 3, 8), c("white", "#ad61ac", "#70196f"))
col_sex = c('Female'='#1D2F6F', 'Male'='#8390FA')
col_age = colorRamp2(c(40, 65, 90), c("white", "#5BC0BE", "#3A506B"))


ha = HeatmapAnnotation(
  Prognosis = CDE$n_op2,
  SILA = CDE$SILA,
  Stage = CDE$Stages_simplified,
  Histology = CDE$Hist_predominant,
  Smoking_Status = CDE$Smoking_Status,
  Nodule_size_cm = CDE$Path_Nodule_Size_cm,
  Sex = CDE$Gender,
  Age = CDE$Age_at_collection,
  col = list(Prognosis = col_prog, 
             SILA = col_sila,
             Stage = col_stage,
             Histology = col_hist,
             Smoking_Status = col_smok,
             Nodule_size_cm = col_nodsiz,
             Sex = col_sex,
             Age = col_age
             ),
  gp = gpar(col = "black"),
  simple_anno_size = unit(0.3, "cm"),
  annotation_name_gp = gpar(fontsize = 8) #size of annotation name
)

bp_top = HeatmapAnnotation(sum = anno_barplot(apply(CDE_omics, 1, sum), border=FALSE),
                           show_annotation_name = FALSE,
                           gp = gpar(fill =2:3, col =2:3))

ht_opt(heatmap_column_names_gp = gpar(fontsize = 5), 
    heatmap_column_title_gp = gpar(fontsize = 10, fontface = "bold"),
    heatmap_row_names_gp = gpar(fontsize = 10, fontface = "bold"),
    legend_title_gp = gpar(fontsize = 8, fontface = "bold"),
    legend_labels_gp = gpar(fontsize = 8)
)
#ht_opt(RESET = TRUE)

ht = Heatmap(mat, name = "Data \ncollected", col = c('grey', 'red'),
        column_split = factor(CDE$n_op2, levels= c('ind', 'int', 'agg')),
        column_title = c('Indolent', 'Intermediate', 'Aggressive'),
        row_labels = c('CyTOF \n(n=70)', 'RNA-Seq \n(n=77)', 'WES \n(n=56) ', 'MxIF \n(n=92)', 'scRNA-Seq \n(n=15)'),
        width = unit(18, "cm"), 
        height = unit(5, "cm"),
        bottom_annotation = ha, 
        top_annotation = bp_top,
        show_row_dend = FALSE,
        show_column_dend = FALSE,
        column_order = order(CDE$SILA),
        row_order = c(1:5),
        rect_gp = gpar(col = "white", lwd = 1)
        )
draw(ht, padding = unit(c(2, 20, 2, 2), "mm"))
#draw(ht, padding = unit(c(6, 20, 6, 20), "cm"))
```

# Histogram of SILA scores (paper)
```{r, fig.width = 5, fig.height = 4}
hist(CDE$SILA, xlab="SILA score", main = 'SILA Score', xlim=c(0,1), col="gray", border="white", las=1, xaxt = "n")
axis(1, at = seq(0, 1, .1))
abline(v=0.4, col = "#3197d6",lwd=5,lty="dashed")
abline(v=0.6, col = "#ab384a",lwd=5,lty="dashed")
```

